-- Store the child's current grade and serve curriculum-aware subject suggestions
-- from database configuration. UI components must not embed a subject list.

alter table public.profiles
  add column if not exists grade_level smallint;

alter table public.profiles
  drop constraint if exists profiles_grade_level_check;

alter table public.profiles
  add constraint profiles_grade_level_check
  check (grade_level is null or grade_level between 1 and 12);

comment on column public.profiles.grade_level is
  'Current Vietnamese general-education grade (1-12); education stage is derived automatically.';

create table if not exists private.curriculum_subject_catalog (
  id bigint generated by default as identity primary key,
  subject_name text not null check (length(trim(subject_name)) > 0),
  education_stage text not null check (education_stage in ('primary', 'lower_secondary', 'upper_secondary')),
  min_grade smallint not null check (min_grade between 1 and 12),
  max_grade smallint not null check (max_grade between 1 and 12 and max_grade >= min_grade),
  curriculum_group text not null check (curriculum_group in ('required', 'elective', 'optional')),
  sort_order integer not null default 0,
  source_document text not null,
  source_url text not null,
  effective_from date not null,
  updated_at timestamptz not null default now(),
  unique (subject_name, education_stage, min_grade, max_grade, curriculum_group)
);

alter table private.curriculum_subject_catalog enable row level security;
revoke all on table private.curriculum_subject_catalog from public, anon, authenticated;
revoke all on sequence private.curriculum_subject_catalog_id_seq from public, anon, authenticated;

drop policy if exists "deny direct curriculum catalog access" on private.curriculum_subject_catalog;
create policy "deny direct curriculum catalog access"
  on private.curriculum_subject_catalog
  for all
  to public
  using (false)
  with check (false);

comment on table private.curriculum_subject_catalog is
  'Vietnamese general-education subject catalog sourced from the consolidated 2018 curriculum and Circular 13/2022.';

insert into private.curriculum_subject_catalog (
  subject_name, education_stage, min_grade, max_grade, curriculum_group,
  sort_order, source_document, source_url, effective_from
)
values
  ('Tiếng Việt', 'primary', 1, 5, 'required', 10, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Toán', 'primary', 1, 5, 'required', 20, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Đạo đức', 'primary', 1, 5, 'required', 30, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Ngoại ngữ 1', 'primary', 1, 2, 'optional', 40, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Ngoại ngữ 1', 'primary', 3, 5, 'required', 40, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Tự nhiên và Xã hội', 'primary', 1, 3, 'required', 50, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Lịch sử và Địa lí', 'primary', 4, 5, 'required', 60, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Khoa học', 'primary', 4, 5, 'required', 70, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Tin học và Công nghệ', 'primary', 3, 5, 'required', 80, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Giáo dục thể chất', 'primary', 1, 5, 'required', 90, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Nghệ thuật', 'primary', 1, 5, 'required', 100, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Hoạt động trải nghiệm', 'primary', 1, 5, 'required', 110, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Tiếng dân tộc thiểu số', 'primary', 1, 5, 'optional', 120, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),

  ('Ngữ văn', 'lower_secondary', 6, 9, 'required', 10, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Toán', 'lower_secondary', 6, 9, 'required', 20, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Ngoại ngữ 1', 'lower_secondary', 6, 9, 'required', 30, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Giáo dục công dân', 'lower_secondary', 6, 9, 'required', 40, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Lịch sử và Địa lí', 'lower_secondary', 6, 9, 'required', 50, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Khoa học tự nhiên', 'lower_secondary', 6, 9, 'required', 60, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Công nghệ', 'lower_secondary', 6, 9, 'required', 70, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Tin học', 'lower_secondary', 6, 9, 'required', 80, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Giáo dục thể chất', 'lower_secondary', 6, 9, 'required', 90, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Nghệ thuật', 'lower_secondary', 6, 9, 'required', 100, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Hoạt động trải nghiệm, hướng nghiệp', 'lower_secondary', 6, 9, 'required', 110, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Nội dung giáo dục của địa phương', 'lower_secondary', 6, 9, 'required', 120, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Tiếng dân tộc thiểu số', 'lower_secondary', 6, 9, 'optional', 130, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),
  ('Ngoại ngữ 2', 'lower_secondary', 6, 9, 'optional', 140, 'Chương trình giáo dục phổ thông 2018 - Chương trình tổng thể', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2019-02-15'),

  ('Ngữ văn', 'upper_secondary', 10, 12, 'required', 10, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Toán', 'upper_secondary', 10, 12, 'required', 20, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Ngoại ngữ 1', 'upper_secondary', 10, 12, 'required', 30, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Lịch sử', 'upper_secondary', 10, 12, 'required', 40, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Giáo dục thể chất', 'upper_secondary', 10, 12, 'required', 50, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Giáo dục quốc phòng và an ninh', 'upper_secondary', 10, 12, 'required', 60, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Hoạt động trải nghiệm, hướng nghiệp', 'upper_secondary', 10, 12, 'required', 70, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Nội dung giáo dục của địa phương', 'upper_secondary', 10, 12, 'required', 80, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Địa lí', 'upper_secondary', 10, 12, 'elective', 90, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Giáo dục kinh tế và pháp luật', 'upper_secondary', 10, 12, 'elective', 100, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Vật lí', 'upper_secondary', 10, 12, 'elective', 110, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Hóa học', 'upper_secondary', 10, 12, 'elective', 120, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Sinh học', 'upper_secondary', 10, 12, 'elective', 130, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Công nghệ', 'upper_secondary', 10, 12, 'elective', 140, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Tin học', 'upper_secondary', 10, 12, 'elective', 150, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Âm nhạc', 'upper_secondary', 10, 12, 'elective', 160, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Mĩ thuật', 'upper_secondary', 10, 12, 'elective', 170, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Tiếng dân tộc thiểu số', 'upper_secondary', 10, 12, 'optional', 180, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03'),
  ('Ngoại ngữ 2', 'upper_secondary', 10, 12, 'optional', 190, 'Chương trình giáo dục phổ thông 2018, sửa đổi bởi Thông tư 13/2022/TT-BGDĐT', 'https://moet.gov.vn/content/vanban/Lists/VBPQ/Attachments/1483/vbhn-chuong-trinh-tong-the.pdf', '2022-08-03')
on conflict (subject_name, education_stage, min_grade, max_grade, curriculum_group)
do update set
  sort_order = excluded.sort_order,
  source_document = excluded.source_document,
  source_url = excluded.source_url,
  effective_from = excluded.effective_from,
  updated_at = now();

create or replace function private.add_child_profile_with_grade(
  p_child_name text,
  p_grade_level smallint
)
returns table (
  account_space_id uuid,
  parent_profile_id uuid,
  child_profile_id uuid,
  child_name text,
  child_grade_level smallint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_created record;
begin
  if p_grade_level is null or p_grade_level not between 1 and 12 then
    raise exception 'Grade level must be between 1 and 12';
  end if;

  select * into strict v_created
  from private.add_child_profile(p_child_name);

  update public.profiles
  set grade_level = p_grade_level, updated_at = now()
  where id = v_created.child_profile_id;

  return query select
    v_created.account_space_id,
    v_created.parent_profile_id,
    v_created.child_profile_id,
    v_created.child_name,
    p_grade_level;
end;
$$;

revoke all on function private.add_child_profile_with_grade(text, smallint)
  from public, anon, authenticated, service_role;
grant execute on function private.add_child_profile_with_grade(text, smallint) to authenticated;

create or replace function public.add_child_profile_with_grade(
  p_child_name text,
  p_grade_level smallint
)
returns table (
  account_space_id uuid,
  parent_profile_id uuid,
  child_profile_id uuid,
  child_name text,
  child_grade_level smallint
)
language sql
security invoker
set search_path = ''
as $$
  select * from private.add_child_profile_with_grade(p_child_name, p_grade_level);
$$;

revoke all on function public.add_child_profile_with_grade(text, smallint) from public, anon;
grant execute on function public.add_child_profile_with_grade(text, smallint) to authenticated;

create or replace function private.update_child_profile_details(
  p_child_profile_id uuid,
  p_child_name text,
  p_grade_level smallint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_grade_level is null or p_grade_level not between 1 and 12 then
    raise exception 'Grade level must be between 1 and 12';
  end if;

  if not private.update_child_profile(p_child_profile_id, p_child_name) then
    return false;
  end if;

  update public.profiles
  set grade_level = p_grade_level, updated_at = now()
  where id = p_child_profile_id;

  return found;
end;
$$;

revoke all on function private.update_child_profile_details(uuid, text, smallint)
  from public, anon, authenticated, service_role;
grant execute on function private.update_child_profile_details(uuid, text, smallint) to authenticated;

create or replace function public.update_child_profile_details(
  p_child_profile_id uuid,
  p_child_name text,
  p_grade_level smallint
)
returns boolean
language sql
security invoker
set search_path = ''
as $$
  select private.update_child_profile_details(p_child_profile_id, p_child_name, p_grade_level);
$$;

revoke all on function public.update_child_profile_details(uuid, text, smallint) from public, anon;
grant execute on function public.update_child_profile_details(uuid, text, smallint) to authenticated;

drop function if exists public.get_account_children();
create function public.get_account_children()
returns table (
  account_space_id uuid,
  parent_profile_id uuid,
  child_profile_id uuid,
  child_name text,
  child_avatar_url text,
  child_grade_level smallint,
  child_joined_at timestamptz
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    family.id,
    (select auth.uid()),
    child_profile.id,
    child_profile.full_name,
    child_profile.avatar_url,
    child_profile.grade_level,
    child_member.joined_at
  from public.families family
  join public.family_members child_member
    on child_member.family_id = family.id
   and child_member.role = 'child'
   and child_member.status = 'active'
  join public.profiles child_profile
    on child_profile.id = child_member.profile_id
  where family.created_by = (select auth.uid())
  order by child_member.joined_at, child_profile.id;
$$;

revoke all on function public.get_account_children() from public, anon;
grant execute on function public.get_account_children() to authenticated;

create or replace function private.get_subject_suggestions(p_child_profile_id uuid)
returns table (
  subject_name text,
  education_stage text,
  curriculum_group text,
  sort_order integer
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_grade_level smallint;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required';
  end if;

  select child_profile.grade_level
  into v_grade_level
  from public.families family
  join public.family_members child_member
    on child_member.family_id = family.id
   and child_member.profile_id = p_child_profile_id
   and child_member.role = 'child'
   and child_member.status = 'active'
  join public.profiles child_profile
    on child_profile.id = child_member.profile_id
  where family.created_by = (select auth.uid())
    and private.can_access_child(family.id, p_child_profile_id)
  limit 1;

  if not found then
    raise exception 'Child profile is not owned by this account';
  end if;

  if v_grade_level is null then
    return;
  end if;

  return query
  select
    catalog.subject_name,
    catalog.education_stage,
    catalog.curriculum_group,
    catalog.sort_order
  from private.curriculum_subject_catalog catalog
  where v_grade_level between catalog.min_grade and catalog.max_grade
  order by
    case catalog.curriculum_group
      when 'required' then 1
      when 'elective' then 2
      else 3
    end,
    catalog.sort_order,
    catalog.subject_name;
end;
$$;

revoke all on function private.get_subject_suggestions(uuid)
  from public, anon, authenticated, service_role;
grant execute on function private.get_subject_suggestions(uuid) to authenticated;

create or replace function public.get_subject_suggestions(p_child_profile_id uuid)
returns table (
  subject_name text,
  education_stage text,
  curriculum_group text,
  sort_order integer
)
language sql
stable
security invoker
set search_path = ''
as $$
  select * from private.get_subject_suggestions(p_child_profile_id);
$$;

revoke all on function public.get_subject_suggestions(uuid) from public, anon;
grant execute on function public.get_subject_suggestions(uuid) to authenticated;

notify pgrst, 'reload schema';
